// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/activity/index.ts";
import entry1 from "./actions/agents/index.ts";
import entry2 from "./actions/overview/index.ts";
import entry3 from "./actions/participants/index.ts";
import entry4 from "./actions/threads/index.ts";
import entry5 from "./actions/usage/index.ts";
const definition = {
  id: "@copilotz/admin",
  version: "3.0.0",
  actions: {
    "adminActivity": entry0,
    "adminAgents": entry1,
    "adminOverview": entry2,
    "adminParticipants": entry3,
    "adminThreads": entry4,
    "adminUsage": entry5,
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
