export const GRAPH_EDGE = {
  PARTICIPATES_IN: "participates_in",
  HAS_CHILD_THREAD: "has_child_thread",
  HAS_MESSAGE: "has_message",
  SENT_BY: "sent_by",
  HAS_TOOL_CALL: "has_tool_call",
  HAS_TOOL_RESULT: "has_tool_result",
  HAS_TOOL_EXECUTION: "has_tool_execution",
  HAS_LLM_ATTEMPT: "has_llm_attempt",
  HAS_USAGE: "has_usage",
  GENERATED_USAGE: "generated_usage",
  INITIATED_USAGE: "initiated_usage",
  HAS_ASSET: "has_asset",
  HAS_VARIANT: "has_variant",
  CREATED_ASSET: "created_asset",
  HAS_DOCUMENT: "has_document",
  HAS_CHUNK: "has_chunk",
  USES_KNOWLEDGE_SPACE: "uses_knowledge_space",
  CAN_ACCESS: "can_access",
  CREATED_BY: "created_by",
  DERIVED_FROM: "derived_from",
  FORKED_FROM: "forked_from",
  MENTIONS: "mentions",
  USES_MEMORY_SPACE: "uses_memory_space",
  HAS_BRAIN_NODE: "has_brain_node",
  HAS_LONG_TERM_MEMORY: "has_long_term_memory",
  INCLUDES_BRAIN_NODE: "includes_brain_node",
  RELATED_TO: "related_to",
  SUPPORTS: "supports",
  CONTRADICTS: "contradicts",
  DEPENDS_ON: "depends_on",
  SUPERSEDES: "supersedes",
} as const;

export type GraphEdgeType = typeof GRAPH_EDGE[keyof typeof GRAPH_EDGE];
