// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./adapters/channels/discord/index.ts";
import entry1 from "./dependencies/channels/index.ts";
import entry2 from "./resources/channels/discord/index.ts";
const definition = {
  id: "@copilotz/channel-discord",
  version: "4.0.0",
  resources: {
    "channels": {
      "discord": entry2,
    },
  },
  adapters: {
    "channels": {
      "discord": entry0,
    },
  },
  plugins: [entry1],
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
