// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./resources/tools/list-skills/index.ts";
import entry1 from "./resources/tools/load-skill/index.ts";
import entry2 from "./resources/tools/read-skill-resource/index.ts";
const definition = {
  id: "@copilotz/skills",
  version: "0.57.0",
  resources: {
    "tools": {
      "list_skills": entry0,
      "load_skill": entry1,
      "read_skill_resource": entry2,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
