// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./resources/capabilities/default/index.ts";
import entry1 from "./resources/promptContext/skillsCatalog/index.ts";
import entry2 from "./resources/promptInstructions/skill-usage/index.ts";
import entry3 from "./resources/tools/list-skills/index.ts";
import entry4 from "./resources/tools/load-skill/index.ts";
import entry5 from "./resources/tools/read-skill-resource/index.ts";
import { corePlugin as dependency0 } from "../core/plugin.ts";
const definition = {
  id: "@copilotz/skills",
  version: "0.57.0",
  plugins: [dependency0],
  resources: {
    "capabilities": {
      "default": entry0,
    },
    "promptContext": {
      "skillsCatalog": entry1,
    },
    "promptInstructions": {
      "skillUsage": entry2,
    },
    "tools": {
      "list_skills": entry3,
      "load_skill": entry4,
      "read_skill_resource": entry5,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
