// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./resources/tools/finance/index.ts";
const definition = {
  id: "@copilotz/finance-tools",
  version: "3.0.0",
  resources: {
    "tools": {
      "finance": entry0,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
