// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./adapters/channels/whatsapp/index.ts";
import entry1 from "./resources/channels/whatsapp/index.ts";
import { channelsPlugin as dependency0 } from "../channel-core/plugin.ts";
const definition = {
  id: "@copilotz/channel-whatsapp",
  version: "4.0.0",
  plugins: [dependency0],
  resources: {
    "channels": {
      "whatsapp": entry1,
    },
  },
  adapters: {
    "channels": {
      "whatsapp": entry0,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
