// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/egress/index.ts";
import entry1 from "./actions/ingress/index.ts";
import entry2 from "./collections/channel-binding/index.ts";
import entry3 from "./dependencies/core/index.ts";
import entry4 from "./processors/egress/index.ts";
import entry5 from "./processors/ingress/index.ts";
const definition = {
  id: "@copilotz/channels",
  version: "0.65.1",
  collections: {
    "channelBinding": entry2,
  },
  actions: {
    "channelEgress": entry0,
    "channelIngress": entry1,
  },
  processors: {
    "channelEgress": entry4,
    "channelIngress": entry5,
  },
  plugins: [entry3],
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
