// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./resources/tools/apply-patch/index.ts";
import entry1 from "./resources/tools/list-directory/index.ts";
import entry2 from "./resources/tools/read-file/index.ts";
import entry3 from "./resources/tools/restore-file-version/index.ts";
import entry4 from "./resources/tools/run-command/index.ts";
import entry5 from "./resources/tools/search-code/index.ts";
import entry6 from "./resources/tools/search-files/index.ts";
import entry7 from "./resources/tools/show-file-diff/index.ts";
import entry8 from "./resources/tools/write-file/index.ts";
const definition = {
  id: "@copilotz/deno-tools",
  version: "3.0.0",
  resources: {
    "tools": {
      "apply_patch": entry0,
      "list_directory": entry1,
      "read_file": entry2,
      "restore_file_version": entry3,
      "run_command": entry4,
      "search_code": entry5,
      "search_files": entry6,
      "show_file_diff": entry7,
      "write_file": entry8,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
