/**
 * Built-in resource manifest for the Copilotz library.
 * Declares all resources that ship with the framework.
 */
export default {
  provides: {
    agents: ["copilotz"],
    tools: [
      "delegate",
      "create_thread",
      "end_thread",
      "http_request",
      "read_file",
      "write_file",
      "list_directory",
      "get_current_time",
      "search_files",
      "search_code",
      "apply_patch",
      "show_file_diff",
      "restore_file_version",
      "fetch_text",
      "run_command",
      "persistent_terminal",
      "wait",
      "save_asset",
      "fetch_asset",
      "search_knowledge",
      "ingest_document",
      "list_namespaces",
      "delete_document",
      "update_my_memory",
      "list_skills",
      "load_skill",
      "read_skill_resource",
    ],
    processors: [
      "new_message",
      "llm_call",
      "llm_result",
      "tool_call",
      "tool_result",
      "rag_ingest",
      "entity_extract",
    ],
    llm: [
      "openai",
      "anthropic",
      "gemini",
      "groq",
      "deepseek",
      "ollama",
      "minimax",
    ],
    embeddings: ["openai"],
    storage: ["fs", "s3"],
    collections: ["participant", "message", "chunk", "document", "llm_usage"],
    channels: ["web", "whatsapp", "zendesk"],
    features: ["admin"],
    skills: [
      "add-api-integration",
      "add-processor",
      "advanced-chat-features",
      "build-copilotz-system",
      "configure-chat-ui",
      "configure-mcp",
      "configure-rag",
      "create-channel",
      "create-embedding-provider",
      "create-agent",
      "create-feature",
      "create-llm-provider",
      "create-storage-adapter",
      "create-tool",
      "debug-runtime-issue",
      "explore-codebase",
      "implement-feature",
      "integrate-external-service",
      "multi-agent-setup",
      "refactor-resource-architecture",
      "review-copilotz-project",
      "ship-chat-experience",
      "setup-collection",
    ],
  },
  presets: {
    core: [
      "agents.copilotz",
      "channels.web",
      "collections.participant",
      "collections.message",
      "collections.llm_usage",
      "tools.list_skills",
      "tools.load_skill",
      "tools.read_skill_resource",
      "tools.persistent_terminal",
      "tools.update_my_memory",
      "processors.new_message",
      "processors.llm_call",
      "processors.llm_result",
      "processors.tool_call",
      "processors.tool_result",
      "skills",
      "llm",
      "storage",
    ],
    rag: [
      "embeddings.openai",
      "collections.document",
      "collections.chunk",
      "tools.search_knowledge",
      "tools.ingest_document",
      "tools.list_namespaces",
      "tools.delete_document",
      "processors.rag_ingest",
      "processors.entity_extract",
    ],
    admin: [
      "features.admin",
    ],
    code: [
      "tools.read_file",
      "tools.write_file",
      "tools.list_directory",
      "tools.search_files",
      "tools.search_code",
      "tools.apply_patch",
      "tools.show_file_diff",
      "tools.restore_file_version",
      "tools.fetch_text",
      "tools.run_command",
      "tools.wait",
    ],
  },
};
