/**
 * Built-in resource manifest for the Copilotz library.
 * Declares all resources that ship with the framework.
 */
export default {
  provides: {
    agents: ["copilotz", "west", "north", "east", "south"],
    tools: [
      "delegate_task",
      "create_thread",
      "end_thread",
      "web_search",
      "http_request",
      "read_file",
      "write_file",
      "list_directory",
      "get_current_time",
      "search_files",
      "search_code",
      "apply_patch",
      "show_file_diff",
      "restore_file_version",
      "fetch_text",
      "run_command",
      "persistent_terminal",
      "wait",
      "save_asset",
      "fetch_asset",
      "search_knowledge",
      "ingest_document",
      "list_knowledge_spaces",
      "delete_document",
      "update_my_memory",
      "update_user_memory",
      "list_skills",
      "load_skill",
      "read_skill_resource",
      "read_tool_result",
      "scheduled_jobs",
      "finance",
    ],
    processors: [
      "memory_reservation/message.created",
      "message_router/message.created",
      "llm_call/llm_attempt.created",
      "llm_result/llm_attempt.completed",
      "llm_result/llm_attempt.failed",
      "tool_call/tool_execution.created",
      "tool_result/tool_execution.completed",
      "tool_result/tool_execution.failed",
      "rag_ingest/rag_ingestion.created",
      "entity_extract/entity_extraction.created",
      "memory_consolidation/long_term_memory.created",
    ],
    memory: ["participant", "history", "retrieval", "long_term"],
    llm: [
      "openai",
      "anthropic",
      "gemini",
      "groq",
      "deepseek",
      "ollama",
      "minimax",
    ],
    embeddings: ["openai"],
    storage: ["fs", "s3"],
    collections: [
      "participant",
      "thread",
      "message",
      "asset",
      "llm_attempt",
      "tool_execution",
      "chunk",
      "document",
      "llm_usage",
      "usage",
      "scheduled_job",
      "memory_space",
      "brain_node",
      "long_term_memory",
    ],
    channels: ["web", "whatsapp", "zendesk", "discord", "telegram"],
    features: ["admin"],
    skills: [
      "add-api-integration",
      "add-processor",
      "advanced-chat-features",
      "build-copilotz-system",
      "configure-chat-ui",
      "configure-mcp",
      "configure-rag",
      "create-channel",
      "create-embedding-provider",
      "create-agent",
      "create-feature",
      "create-llm-provider",
      "create-memory",
      "create-storage-adapter",
      "create-tool",
      "debug-runtime-issue",
      "explore-codebase",
      "implement-feature",
      "integrate-external-service",
      "multi-agent-setup",
      "refactor-resource-architecture",
      "review-copilotz-project",
      "ship-chat-experience",
      "setup-collection",
    ],
  },
  presets: {
    core: [
      "channels.web",
      "collections.participant",
      "collections.thread",
      "collections.message",
      "collections.asset",
      "collections.llm_attempt",
      "collections.tool_execution",
      "collections.llm_usage",
      "collections.usage",
      "collections.memory_space",
      "collections.brain_node",
      "collections.long_term_memory",
      "memory.participant",
      "memory.history",
      "memory.long_term",
      "tools.list_skills",
      "tools.load_skill",
      "tools.read_skill_resource",
      "tools.read_tool_result",
      "tools.web_search",
      "tools.fetch_text",
      "tools.http_request",
      "tools.persistent_terminal",
      "tools.update_my_memory",
      "tools.update_user_memory",
      "processors.memory_reservation/message.created",
      "processors.message_router/message.created",
      "processors.llm_call/llm_attempt.created",
      "processors.llm_result/llm_attempt.completed",
      "processors.llm_result/llm_attempt.failed",
      "processors.tool_call/tool_execution.created",
      "processors.tool_result/tool_execution.completed",
      "processors.tool_result/tool_execution.failed",
      "processors.memory_consolidation/long_term_memory.created",
      "skills",
      "llm",
      "storage",
    ],
    rag: [
      "embeddings.openai",
      "collections.document",
      "collections.chunk",
      "memory.retrieval",
      "tools.search_knowledge",
      "tools.ingest_document",
      "tools.list_knowledge_spaces",
      "tools.delete_document",
      "processors.rag_ingest/rag_ingestion.created",
      "processors.entity_extract/entity_extraction.created",
    ],
    admin: [
      "features.admin",
    ],
    finance: [
      "tools.finance",
    ],
    code: [
      "tools.read_file",
      "tools.write_file",
      "tools.list_directory",
      "tools.search_files",
      "tools.search_code",
      "tools.apply_patch",
      "tools.show_file_diff",
      "tools.restore_file_version",
      "tools.web_search",
      "tools.fetch_text",
      "tools.run_command",
      "tools.wait",
      "tools.http_request",
      "tools.read_tool_result",
      "tools.get_current_time",
    ],
    "skunk-works": [
      // Agents (west first = default routing target)
      "agents.west",
      "agents.north",
      "agents.east",
      "agents.south",
      // Tools
      "tools.delegate_task",
      "tools.create_thread",
      "tools.end_thread",
      "tools.web_search",
      "tools.fetch_text",
      "tools.http_request",
      "tools.read_tool_result",
      "tools.get_current_time",
      "tools.read_file",
      "tools.write_file",
      "tools.apply_patch",
      "tools.show_file_diff",
      "tools.restore_file_version",
      "tools.list_directory",
      "tools.search_files",
      "tools.search_code",
      "tools.run_command",
      "tools.wait",
      "tools.persistent_terminal",
      "tools.list_skills",
      "tools.load_skill",
      "tools.read_skill_resource",
      "tools.update_my_memory",
      "tools.update_user_memory",
    ],
  },
};
