/**
 * Built-in resource manifest for the Copilotz library.
 * Declares all resources that ship with the framework.
 */
export default {
  provides: {
    agents: ["copilotz"],
    tools: [
      "delegate",
      "create_thread",
      "end_thread",
      "http_request",
      "read_file",
      "write_file",
      "list_directory",
      "get_current_time",
      "search_files",
      "search_code",
      "apply_patch",
      "show_file_diff",
      "restore_file_version",
      "fetch_text",
      "run_command",
      "persistent_terminal",
      "wait",
      "save_asset",
      "fetch_asset",
      "search_knowledge",
      "ingest_document",
      "list_namespaces",
      "delete_document",
      "update_my_memory",
      "list_skills",
      "load_skill",
      "read_skill_resource",
    ],
    processors: [
      "new_message",
      "llm_call",
      "llm_result",
      "tool_call",
      "tool_result",
      "rag_ingest",
      "entity_extract",
    ],
    llm: [
      "openai",
      "anthropic",
      "gemini",
      "groq",
      "deepseek",
      "ollama",
      "minimax",
    ],
    embeddings: ["openai"],
    storage: ["fs", "s3"],
    collections: ["participant", "message", "chunk", "document", "llm_usage"],
    channels: ["web", "whatsapp", "zendesk"],
    features: ["admin"],
    skills: [
      "add-api-integration",
      "add-processor",
      "advanced-chat-features",
      "configure-chat-ui",
      "configure-mcp",
      "configure-rag",
      "create-agent",
      "create-tool",
      "multi-agent-setup",
      "setup-collection",
    ],
  },
};
