import { defineCollection, relation } from "@/database/collections/index.ts";
import { GRAPH_EDGE } from "@/runtime/graph/edges.ts";

export default defineCollection({
  name: "brain_node",
  schema: {
    type: "object",
    properties: {
      id: { type: "string" },
      memorySpaceId: { type: "string" },
      checkpointId: { type: "string" },
      createdByAgentId: { type: "string" },
      originThreadId: { type: "string" },
      layer: {
        type: "string",
        enum: ["knowledge", "working"],
      },
      status: {
        type: "string",
        enum: ["active", "superseded", "archived"],
      },
      kind: {
        type: "string",
        enum: [
          "entity",
          "fact",
          "claim",
          "decision",
          "preference",
          "task",
          "event",
          "constraint",
          "challenge",
          "purpose",
          "desired_outcome",
          "success_criterion",
          "decision_criterion",
          "current_state",
          "active_approach",
          "risk",
          "open_question",
          "next_action",
        ],
      },
      name: { type: "string" },
      content: { type: "string" },
      confidence: { type: ["number", "null"] },
      sourceMessageIds: { type: "array", items: { type: "string" } },
      sourceField: { type: ["string", "null"] },
      embedding: { type: ["array", "null"] },
    },
    required: [
      "memorySpaceId",
      "checkpointId",
      "createdByAgentId",
      "originThreadId",
      "layer",
      "status",
      "kind",
      "name",
      "content",
      "sourceMessageIds",
    ],
  } as const,
  indexes: [
    "memorySpaceId",
    "checkpointId",
    "createdByAgentId",
    "originThreadId",
    ["memorySpaceId", "createdByAgentId"],
    ["layer", "kind"],
    "status",
    "kind",
  ],
  relations: {
    memorySpace: relation.belongsTo(
      "memory_space",
      "memorySpaceId",
      GRAPH_EDGE.HAS_BRAIN_NODE,
    ),
    checkpoint: relation.belongsTo(
      "long_term_memory",
      "checkpointId",
      GRAPH_EDGE.INCLUDES_BRAIN_NODE,
    ),
  },
  search: {
    enabled: true,
    fields: ["name", "content"],
  },
});
