// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./resources/tools/fetch-text/index.ts";
import entry1 from "./resources/tools/http-request/index.ts";
import entry2 from "./resources/tools/web-search/index.ts";
const definition = {
  id: "@copilotz/web-tools",
  version: "3.0.0",
  resources: {
    "tools": {
      "fetch_text": entry0,
      "http_request": entry1,
      "web_search": entry2,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
