// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/consolidate-memory/index.ts";
import entry1 from "./actions/inspect-memory/index.ts";
import entry2 from "./actions/invalidate-memory/index.ts";
import entry3 from "./actions/list-knowledge-spaces/index.ts";
import entry4 from "./actions/search-memory/index.ts";
import entry5 from "./actions/set-memory-status/index.ts";
import entry6 from "./collections/long-term-memory/index.ts";
import entry7 from "./collections/memory-record/index.ts";
import entry8 from "./collections/memory-space-access/index.ts";
import entry9 from "./collections/memory-space/index.ts";
import entry10 from "./dependencies/core/index.ts";
import entry11 from "./processors/dispatch-consolidation/index.ts";
import entry12 from "./processors/reserve-memory/index.ts";
import entry13 from "./processors/settle-consolidation/index.ts";
import entry14 from "./resources/memory/config/index.ts";
import entry15 from "./resources/memory/kinds/index.ts";
import entry16 from "./resources/promptContext/memory/index.ts";
import entry17 from "./resources/tools/consolidate-memory/index.ts";
import entry18 from "./resources/tools/inspect-memory/index.ts";
import entry19 from "./resources/tools/invalidate-memory/index.ts";
import entry20 from "./resources/tools/list-knowledge-spaces/index.ts";
import entry21 from "./resources/tools/search-memory/index.ts";
import entry22 from "./resources/tools/set-memory-status/index.ts";
const definition = {
  id: "@copilotz/core-long-term-memory",
  version: "4.0.0",
  collections: {
    "longTermMemory": entry6,
    "memoryRecord": entry7,
    "memorySpaceAccess": entry8,
    "memorySpace": entry9,
  },
  actions: {
    "consolidate_memory": entry0,
    "inspect_memory": entry1,
    "invalidate_memory": entry2,
    "list_knowledge_spaces": entry3,
    "search_memory": entry4,
    "set_memory_status": entry5,
  },
  processors: {
    "dispatchConsolidation": entry11,
    "reserveMemory": entry12,
    "settleConsolidation": entry13,
  },
  resources: {
    "memory": {
      "config": entry14,
      "kinds": entry15,
    },
    "promptContext": {
      "memory": entry16,
    },
    "tools": {
      "consolidate_memory": entry17,
      "inspect_memory": entry18,
      "invalidate_memory": entry19,
      "list_knowledge_spaces": entry20,
      "search_memory": entry21,
      "set_memory_status": entry22,
    },
  },
  plugins: [entry10],
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
