// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/consolidate-memory/index.ts";
import entry1 from "./actions/inspect-memory/index.ts";
import entry2 from "./actions/list-knowledge-spaces/index.ts";
import entry3 from "./actions/search-memory/index.ts";
import entry4 from "./collections/long-term-memory/index.ts";
import entry5 from "./collections/memory-note/index.ts";
import entry6 from "./collections/memory-space-access/index.ts";
import entry7 from "./collections/memory-space/index.ts";
import entry8 from "./processors/dispatch-consolidation/index.ts";
import entry9 from "./processors/settle-consolidation/index.ts";
import entry10 from "./resources/memory/config/index.ts";
import entry11 from "./resources/promptContext/memory/index.ts";
import entry12 from "./resources/tools/consolidate-memory/index.ts";
import entry13 from "./resources/tools/inspect-memory/index.ts";
import entry14 from "./resources/tools/list-knowledge-spaces/index.ts";
import entry15 from "./resources/tools/search-memory/index.ts";
import { corePlugin as dependency0 } from "../core/plugin.ts";
const definition = {
  id: "@copilotz/core-long-term-memory",
  version: "5.0.0",
  plugins: [dependency0],
  collections: {
    "longTermMemory": entry4,
    "memoryNote": entry5,
    "memorySpaceAccess": entry6,
    "memorySpace": entry7,
  },
  actions: {
    "consolidate_memory": entry0,
    "inspect_memory": entry1,
    "list_knowledge_spaces": entry2,
    "search_memory": entry3,
  },
  processors: {
    "dispatchConsolidation": entry8,
    "settleConsolidation": entry9,
  },
  resources: {
    "memory": {
      "config": entry10,
    },
    "promptContext": {
      "memory": entry11,
    },
    "tools": {
      "consolidate_memory": entry12,
      "inspect_memory": entry13,
      "list_knowledge_spaces": entry14,
      "search_memory": entry15,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
