// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/invoke-action/index.ts";
import entry1 from "./processors/action-request/index.ts";
import entry2 from "./processors/collection-mutation-request/index.ts";
import entry3 from "./resources/server/default/index.ts";
const definition = {
  id: "copilotz.server",
  version: "1.0.0",
  actions: {
    "serverInvoke": entry0,
  },
  processors: {
    "serverActionRequest": entry1,
    "serverCollectionMutationRequest": entry2,
  },
  resources: {
    "server": {
      "default": entry3,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
