// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/dispatch-scheduled-message/index.ts";
import entry1 from "./actions/scheduled-jobs/index.ts";
import entry2 from "./processors/dispatch-scheduled-message/index.ts";
import entry3 from "./processors/pause-space-jobs/index.ts";
import entry4 from "./resources/tools/scheduled-jobs/index.ts";
import { corePlugin as dependency0 } from "../core/plugin.ts";
import { schedulesPlugin as dependency1 } from "../schedules/plugin.ts";
const definition = {
  id: "@copilotz/core-schedules",
  version: "0.65.1",
  plugins: [dependency0, dependency1],
  actions: {
    "dispatchScheduledMessage": entry0,
    "scheduled_jobs": entry1,
  },
  processors: {
    "dispatchScheduledMessage": entry2,
    "pauseSpaceJobs": entry3,
  },
  resources: {
    "tools": {
      "scheduled_jobs": entry4,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
