// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/add-thread-participant/index.ts";
import entry1 from "./actions/ask/index.ts";
import entry2 from "./actions/compact-context/index.ts";
import entry3 from "./actions/create-thread-message/index.ts";
import entry4 from "./actions/create-thread/index.ts";
import entry5 from "./actions/delete-thread-messages/index.ts";
import entry6 from "./actions/read-tool-result/index.ts";
import entry7 from "./actions/revise-message/index.ts";
import entry8 from "./actions/run-goal/index.ts";
import entry9 from "./actions/spaces/index.ts";
import entry10 from "./collections/message/index.ts";
import entry11 from "./collections/participant/index.ts";
import entry12 from "./collections/space-attachment/index.ts";
import entry13 from "./collections/space/index.ts";
import entry14 from "./collections/thread/index.ts";
import entry15 from "./collections/tool-plan-branch/index.ts";
import entry16 from "./collections/tool-plan-stage-result/index.ts";
import entry17 from "./collections/tool-plan/index.ts";
import entry18 from "./processors/complete-ask/index.ts";
import entry19 from "./processors/fail-ask/index.ts";
import entry20 from "./processors/message-input/index.ts";
import entry21 from "./processors/message-router/index.ts";
import entry22 from "./processors/project-agent-failure/index.ts";
import entry23 from "./processors/project-text-result/index.ts";
import entry24 from "./processors/project-tool-result/index.ts";
import entry25 from "./processors/tool-plan-coordinator/index.ts";
import entry26 from "./resources/capabilities/default/index.ts";
import entry27 from "./resources/goals/default/index.ts";
import entry28 from "./resources/toolResults/default/index.ts";
import entry29 from "./resources/tools/ask/index.ts";
import entry30 from "./resources/tools/read-tool-result/index.ts";
import { llmPlugin as dependency0 } from "../llm/plugin.ts";
const definition = {
  id: "@copilotz/core",
  version: "0.75.0",
  plugins: [dependency0],
  collections: {
    "message": entry10,
    "participant": entry11,
    "spaceAttachment": entry12,
    "space": entry13,
    "thread": entry14,
    "toolPlanBranch": entry15,
    "toolPlanStageResult": entry16,
    "toolPlan": entry17,
  },
  actions: {
    "addThreadParticipant": entry0,
    "ask": entry1,
    "compactContext": entry2,
    "createThreadMessage": entry3,
    "createThread": entry4,
    "deleteThreadMessages": entry5,
    "readToolResult": entry6,
    "reviseMessage": entry7,
    "runGoal": entry8,
    "spaces": entry9,
  },
  processors: {
    "completeAsk": entry18,
    "failAsk": entry19,
    "messageInput": entry20,
    "messageRouter": entry21,
    "projectAgentFailure": entry22,
    "projectTextResult": entry23,
    "projectToolResult": entry24,
    "toolPlanCoordinator": entry25,
  },
  resources: {
    "capabilities": {
      "default": entry26,
    },
    "goals": {
      "default": entry27,
    },
    "toolResults": {
      "default": entry28,
    },
    "tools": {
      "ask": entry29,
      "readToolResult": entry30,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
