// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/transcribe/index.ts";
const definition = {
  id: "@copilotz/transcription",
  version: "1.0.0",
  actions: {
    "transcribeAudio": entry0,
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
