// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./resources/tools/persistent-terminal/index.ts";
const definition = {
  id: "@copilotz/persistent-terminal-tools",
  version: "3.0.0",
  resources: {
    "tools": {
      "persistent_terminal": entry0,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
