// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./collections/usage/index.ts";
import entry1 from "./processors/record-llm-usage/index.ts";
import entry2 from "./processors/record-tool-usage/index.ts";
const definition = {
  id: "@copilotz/core-usage",
  version: "3.0.0",
  collections: {
    "usage": entry0,
  },
  processors: {
    "recordLlmUsage": entry1,
    "recordToolUsage": entry2,
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
