// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./resources/tools/create-thread/index.ts";
import entry1 from "./resources/tools/end-thread/index.ts";
import entry2 from "./resources/tools/fetch-asset/index.ts";
import entry3 from "./resources/tools/get-current-time/index.ts";
import entry4 from "./resources/tools/save-asset/index.ts";
import entry5 from "./resources/tools/update-my-memory/index.ts";
import entry6 from "./resources/tools/update-user-memory/index.ts";
import entry7 from "./resources/tools/wait/index.ts";
const definition = {
  id: "@copilotz/built-in-tools",
  version: "3.0.0",
  resources: {
    "tools": {
      "create_thread": entry0,
      "end_thread": entry1,
      "fetch_asset": entry2,
      "get_current_time": entry3,
      "save_asset": entry4,
      "update_my_memory": entry5,
      "update_user_memory": entry6,
      "wait": entry7,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
