// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
const definition = {
  id: "@copilotz/openapi-tools",
  version: "3.0.0",
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
