// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/delete-conversation/index.ts";
import entry1 from "./actions/edit-conversation-message/index.ts";
import entry2 from "./actions/send-conversation/index.ts";
import entry3 from "./actions/update-conversation/index.ts";
import entry4 from "./adapters/http/core/index.ts";
import { corePlugin as dependency0 } from "../core/plugin.ts";
const definition = {
  id: "copilotz.core.http",
  version: "0.75.0",
  plugins: [dependency0],
  actions: {
    "deleteConversation": entry0,
    "editConversationMessage": entry1,
    "sendConversation": entry2,
    "updateConversation": entry3,
  },
  adapters: {
    "http": {
      "core": entry4,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
