// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/call-llm/index.ts";
const definition = {
  id: "@copilotz/llm",
  version: "0.65.1",
  actions: {
    "callLlm": entry0,
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
