// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/add-thread-participant/index.ts";
import entry1 from "./actions/ask/index.ts";
import entry2 from "./actions/create-thread-message/index.ts";
import entry3 from "./actions/create-thread/index.ts";
import entry4 from "./actions/delete-thread-messages/index.ts";
import entry5 from "./actions/revise-message/index.ts";
import entry6 from "./actions/spaces/index.ts";
import entry7 from "./collections/message/index.ts";
import entry8 from "./collections/participant/index.ts";
import entry9 from "./collections/space-attachment/index.ts";
import entry10 from "./collections/space/index.ts";
import entry11 from "./collections/thread/index.ts";
import entry12 from "./collections/tool-plan-stage-result/index.ts";
import entry13 from "./collections/tool-plan/index.ts";
import entry14 from "./processors/message-input/index.ts";
const definition = {
  id: "@copilotz/core-collections",
  version: "0.65.1",
  collections: {
    "message": entry7,
    "participant": entry8,
    "spaceAttachment": entry9,
    "space": entry10,
    "thread": entry11,
    "toolPlanStageResult": entry12,
    "toolPlan": entry13,
  },
  actions: {
    "addThreadParticipant": entry0,
    "ask": entry1,
    "createThreadMessage": entry2,
    "createThread": entry3,
    "deleteThreadMessages": entry4,
    "reviseMessage": entry5,
    "spaces": entry6,
  },
  processors: {
    "messageInput": entry14,
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
