// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/index-document/index.ts";
import entry1 from "./collections/chunk/index.ts";
import entry2 from "./collections/document/index.ts";
import entry3 from "./processors/index-document/index.ts";
import entry4 from "./resources/tools/delete-document/index.ts";
import entry5 from "./resources/tools/ingest-document/index.ts";
import entry6 from "./resources/tools/search-knowledge/index.ts";
const definition = {
  id: "@copilotz/knowledge",
  version: "3.0.0",
  collections: {
    "chunk": entry1,
    "document": entry2,
  },
  actions: {
    "indexKnowledgeDocument": entry0,
  },
  processors: {
    "indexKnowledgeDocument": entry3,
  },
  resources: {
    "tools": {
      "delete_document": entry4,
      "ingest_document": entry5,
      "search_knowledge": entry6,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
