// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./adapters/llm/demo/index.ts";
import entry1 from "./processors/bootstrap/index.ts";
import entry2 from "./resources/agents/support/index.ts";
import entry3 from "./resources/llmConnections/demo/index.ts";
import { corePlugin as dependency0 } from "@copilotz/copilotz/core";
const definition = {
  id: "example.support",
  version: "1.0.0",
  plugins: [dependency0],
  processors: {
    "bootstrap": entry1,
  },
  resources: {
    "agents": {
      "support": entry2,
    },
    "llmConnections": {
      "demo": entry3,
    },
  },
  adapters: {
    "llm": {
      "demo": entry0,
    },
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
