// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./adapters/llm/demo/index.ts";
import entry1 from "./dependencies/core/index.ts";
import entry2 from "./processors/bootstrap/index.ts";
import entry3 from "./resources/agents/support/index.ts";
import entry4 from "./resources/llmConnections/demo/index.ts";
const definition = {
  id: "example.support",
  version: "1.0.0",
  processors: {
    "bootstrap": entry2,
  },
  resources: {
    "agents": {
      "support": entry3,
    },
    "llmConnections": {
      "demo": entry4,
    },
  },
  adapters: {
    "llm": {
      "demo": entry0,
    },
  },
  plugins: [entry1],
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
