// Generated by copilotz build. Edit source declarations, not this file.
import { definePlugin, type DefinedPlugin } from "@copilotz/copilotz/plugins";
import entry0 from "./actions/run-scheduled-job-now/index.ts";
import entry1 from "./actions/tick-scheduled-jobs/index.ts";
import entry2 from "./collections/scheduled-job/index.ts";
import entry3 from "./processors/run-now-input/index.ts";
import entry4 from "./processors/tick-input/index.ts";
const definition = {
  id: "@copilotz/schedules",
  version: "0.65.1",
  collections: {
    "scheduledJob": entry2,
  },
  actions: {
    "runScheduledJobNow": entry0,
    "tickScheduledJobs": entry1,
  },
  processors: {
    "runScheduledJobNowInput": entry3,
    "tickScheduledJobsInput": entry4,
  },
} as const;
const plugin: DefinedPlugin<typeof definition> = definePlugin(definition);
export default plugin;
